declare const global: Record<string, any>
declare const Component: dev.latvian.mods.kubejs.plugin.builtin.wrapper.TextWrapperStatic
declare const TextIcons: dev.latvian.mods.kubejs.plugin.builtin.wrapper.TextIconsStatic
declare const UUID: dev.latvian.mods.kubejs.plugin.builtin.wrapper.UUIDWrapperStatic
declare const JsonUtils: dev.latvian.mods.kubejs.util.JsonUtilsStatic
declare const JsonIO: dev.latvian.mods.kubejs.util.JsonIOStatic
declare const Block: dev.latvian.mods.kubejs.plugin.builtin.wrapper.BlockWrapperStatic
declare const Blocks: net.minecraft.world.level.block.BlocksStatic
declare const Item: dev.latvian.mods.kubejs.plugin.builtin.wrapper.ItemWrapperStatic
declare const Items: net.minecraft.world.item.ItemsStatic
declare const Ingredient: dev.latvian.mods.kubejs.plugin.builtin.wrapper.IngredientWrapperStatic
declare const NBT: dev.latvian.mods.kubejs.plugin.builtin.wrapper.NBTWrapperStatic
declare const NBTIO: dev.latvian.mods.kubejs.util.NBTIOWrapperStatic
declare const Direction: dev.latvian.mods.kubejs.plugin.builtin.wrapper.DirectionWrapperStatic
declare const Facing: dev.latvian.mods.kubejs.plugin.builtin.wrapper.DirectionWrapperStatic
declare const AABB: dev.latvian.mods.kubejs.plugin.builtin.wrapper.AABBWrapperStatic
declare const Stats: net.minecraft.stats.StatsStatic
declare const FluidAmounts: dev.latvian.mods.kubejs.util.FluidAmountsStatic
declare const Notification: dev.latvian.mods.kubejs.util.NotificationToastDataStatic
declare const SizedIngredient: dev.latvian.mods.kubejs.plugin.builtin.wrapper.SizedIngredientWrapperStatic
declare const ParticleOptions: dev.latvian.mods.kubejs.plugin.builtin.wrapper.ParticleOptionsWrapperStatic
declare const Registry: dev.latvian.mods.kubejs.plugin.builtin.wrapper.RegistryWrapperStatic
declare const DataMap: dev.latvian.mods.kubejs.plugin.builtin.wrapper.DataMapWrapperStatic
declare const EntitySelector: dev.latvian.mods.kubejs.plugin.builtin.wrapper.EntitySelectorWrapperStatic
declare const Fluid: dev.latvian.mods.kubejs.fluid.FluidWrapperStatic
declare const SECOND: 1000
declare const MINUTE: 60000
declare const HOUR: 3600000
declare const Color: dev.latvian.mods.kubejs.plugin.builtin.wrapper.ColorWrapperStatic
declare const BlockStatePredicate: dev.latvian.mods.kubejs.block.state.BlockStatePredicateStatic
declare const Vec3d: net.minecraft.world.phys.Vec3Static
declare const Vec3i: net.minecraft.core.Vec3iStatic
declare const Vec3f: org.joml.Vector3fStatic
declare const Vec4f: org.joml.Vector4fStatic
declare const Matrix3f: org.joml.Matrix3fStatic
declare const Matrix4f: org.joml.Matrix4fStatic
declare const Quaternionf: org.joml.QuaternionfStatic
declare const RotationAxis: dev.latvian.mods.kubejs.util.RotationAxisStatic
declare const BlockPos: net.minecraft.core.BlockPosStatic
declare const DamageSource: net.minecraft.world.damagesource.DamageSourcesStatic
declare const SoundType: net.minecraft.world.level.block.SoundTypeStatic
declare const BlockProperties: net.minecraft.world.level.block.state.properties.BlockStatePropertiesStatic
declare const NativeEvents: dev.latvian.mods.kubejs.plugin.builtin.wrapper.NativeEventWrapperStatic
declare const MobEffectUtil: dev.latvian.mods.kubejs.util.MobEffectUtilStatic
declare const Client: net.minecraft.client.MinecraftStatic
declare const GLFWInput: Record<string, number>
declare const JavaAdapter: Function // TODO: check what kind of function this is
declare const Platform: dev.latvian.mods.kubejs.script.PlatformWrapperStatic
declare const StartupEvents: any
declare const ServerEvents: any
declare const LevelEvents: any
declare const NetworkEvents: any
declare const ItemEvents: any
declare const BlockEvents: any
declare const EntityEvents: any
declare const PlayerEvents: any
declare const RecipeViewerEvents: any
declare const ClientEvents: any
declare const KeyBindEvents: any
declare const JavaMath: java.lang.MathStatic
declare const ID: dev.latvian.mods.kubejs.util.IDStatic
declare const Duration: java.time.DurationStatic
declare const KMath: dev.latvian.mods.kubejs.plugin.builtin.wrapper.KMathStatic
declare const Java: dev.latvian.mods.kubejs.plugin.builtin.wrapper.JavaWrapperStatic
declare const Utils: dev.latvian.mods.kubejs.plugin.builtin.wrapper.UtilsWrapperStatic
declare const Text: dev.latvian.mods.kubejs.plugin.builtin.wrapper.TextWrapperStatic
declare const JavaException: Function
declare const With: Function
declare const Call: Function
declare const StringUtils: dev.latvian.mods.kubejs.plugin.builtin.wrapper.StringUtilsWrapperStatic
