declare const global: Record<string, any>
declare const Component: any
declare const TextIcons: any
declare const UUID: any
declare const JsonUtils: any
declare const JsonIO: any
declare const Block: any
declare const Blocks: any
declare const Item: any
declare const Items: any
declare const Ingredient: any
declare const NBT: any
declare const NBTIO: any
declare const Direction: any
declare const Facing: any
declare const AABB: any
declare const Stats: any
declare const FluidAmounts: any
declare const Notification: any
declare const SizedIngredient: any
declare const ParticleOptions: any
declare const Registry: any
declare const DataMap: any
declare const EntitySelector: any
declare const Fluid: any
declare const SECOND: any
declare const MINUTE: any
declare const HOUR: any
declare const Color: any
declare const BlockStatePredicate: any
declare const Vec3d: any
declare const Vec3i: any
declare const Vec3f: any
declare const Vec4f: any
declare const Matrix3f: any
declare const Matrix4f: any
declare const Quaternionf: any
declare const RotationAxis: any
declare const BlockPos: any
declare const DamageSource: any
declare const SoundType: any
declare const BlockProperties: any
declare const NativeEvents: any
declare const MobEffectUtil: any
declare const Client: any
declare const GLFWInput: any
declare const JavaAdapter: any
declare const Platform: any
declare const StartupEvents: any
declare const ServerEvents: any
declare const LevelEvents: any
declare const NetworkEvents: any
declare const ItemEvents: any
declare const BlockEvents: any
declare const EntityEvents: any
declare const PlayerEvents: any
declare const RecipeViewerEvents: any
declare const ClientEvents: any
declare const KeyBindEvents: any
declare const JavaMath: any
declare const ID: any
declare const Duration: any
declare const KMath: any
declare const Java: any
declare const Utils: any
declare const Text: any
declare const JavaException: any
declare const With: any
declare const Call: any
declare const StringUtils: any
